//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esmeraldino.ConsultaCPF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.iwebservice.info", ConfigurationName="ConsultaCPF.iWebServicePortType")]
    public interface iWebServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CEP/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getCep(string cep, string chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CEP/", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCepAsync(string cep, string chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CPF/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getCpf(string cpf, string dataNascimento, string chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CPF/", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCpfAsync(string cpf, string dataNascimento, string chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CNPJ/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getCnpj(string cnpj, string chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.iwebservice.info/CNPJ/", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCnpjAsync(string cnpj, string chave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iWebServicePortTypeChannel : esmeraldino.ConsultaCPF.iWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iWebServicePortTypeClient : System.ServiceModel.ClientBase<esmeraldino.ConsultaCPF.iWebServicePortType>, esmeraldino.ConsultaCPF.iWebServicePortType {
        
        public iWebServicePortTypeClient() {
        }
        
        public iWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCep(string cep, string chave) {
            return base.Channel.getCep(cep, chave);
        }
        
        public System.Threading.Tasks.Task<string> getCepAsync(string cep, string chave) {
            return base.Channel.getCepAsync(cep, chave);
        }
        
        public string getCpf(string cpf, string dataNascimento, string chave) {
            return base.Channel.getCpf(cpf, dataNascimento, chave);
        }
        
        public System.Threading.Tasks.Task<string> getCpfAsync(string cpf, string dataNascimento, string chave) {
            return base.Channel.getCpfAsync(cpf, dataNascimento, chave);
        }
        
        public string getCnpj(string cnpj, string chave) {
            return base.Channel.getCnpj(cnpj, chave);
        }
        
        public System.Threading.Tasks.Task<string> getCnpjAsync(string cnpj, string chave) {
            return base.Channel.getCnpjAsync(cnpj, chave);
        }
    }
}
